### ISSUE TITLE
Translate the website

### ISSUE THREAD

**Issue by airon90** [uniqush/uniqush-www#2]
Hi, I'd like to translate the website into Italian. How can I do that? Where do I put translated .page files? Thank you very much!

**Comment by TysonAndre** [comment]
The project maintainers don't have the resources to maintain translations, update translations when the code changes, or verify the accuracy of translations. Additionally, adding i18n support for the text on the site would take a long time (and no translations are available yet).

Anyone wishing to translate this is free to do so on their own mirrors/forks of the documentation
